import type { Metadata } from "next";
import { gothic } from "./ui/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={gothic.className}>
        {children}
        <div className="w-screen h-24 min-h-fit bg-background-light_gray flex justify-center items-center">
          <p className="text-center text-text-gray">
            문의 사항은 아래 이메일로 보내주세요!
            <br />
            inseon02@mefeto.com
          </p>
        </div>
      </body>
    </html>
  );
}
